### ISSUE TITLE
on iOS 11, `enableLocation` and `enableBluetooth` don't redirect to the specific `Settings` page

### ISSUE THREAD

**Issue by panz3r** [nearit/react-native-connectivity-status#4]
on iOS 11, when calling `enableLocation` and `enableBluetooth` methods `Settings` app launches to the main screen, instead it should launch into the `Location Services` section and into the `Bluetooth` section respectively.

This seems to be an intended change made by Apple and there is currently no solution or workaround.

This issue will stay open until a solution is found, or until a new way to achieve the desired behaviour is found.

**Comment by federicoboschini** [comment]
After iOS 12 announcement, Apple started rejecting apps that use private URL Schemes.
It means that trying to open any `Settings` screen is not permitted.
Version `1.5.0` removes methods for enabling bluetooth and location.

This issue can be closed.
