### ISSUE TITLE
Apple rejection "prefs:root"

### ISSUE THREAD

**Issue by aorlandini-mypass** [nearit/react-native-connectivity-status#5]
Hi, we got an Apple Rejection by using this module:

"Your app uses the "prefs:root=" non-public URL scheme, which is a private entity."

Proposal resolution:

"To resolve this issue, please revise your app to provide the associated functionality using public APIs or remove the functionality using the "prefs:root" or "App-Prefs:root" URL scheme."

Can you help?
Thank you

**Comment by trnc-ck** [comment]
Same here. Is there a way you can fix this?

**Comment by federicoboschini** [comment]
Hi @aorlandini-mypass ,
after iOS 12 announcement, Apple started rejecting apps that use those private URL Schemes.
We just released version `1.5.0`: methods that redirect to Location and Bluetooth settings have been removed, so no private scheme is used in our code.

Thank you for your contribution.
